### ISSUE TITLE
Turkish language pack

### ISSUE THREAD

**Issue by ghost** [devstratum/metadesc#1]
Hi,

Thank you for the plugin. Metadesc Turkish language pack is attached. I will be glad if you add it to the next version.

[tr-TR.zip](https://github.com/devstratum/metadesc/files/8955270/tr-TR.zip)

Best Regards

**Comment by devstratum** [comment]
Hello, Thank you.

I added Turkish language pack in new release Metadesc v1.54.3

**Comment by ghost** [comment]
Hi,

Thank you,
Regards
