### ISSUE TITLE
Сыпет нотисами при создании псевдонима меню

### ISSUE THREAD

**Issue by studio-express** [devstratum/metadesc#2]
Приветствую.

Описание проблемы:
Есть два меню A и B. В меню B ссылки на пункты меню A. Результат на скрине.

Eng:

Hi. 

Problem:

There are two menus A and B. In menu B, links to menu items A. The result is on the screen.

<img width="1577" alt="Screenshot 2022-07-07 at 13 44 57" src="https://user-images.githubusercontent.com/4165508/177838207-efd8b779-87a7-4bb4-8589-d3c6899538da.png">

**Comment by devstratum** [comment]
Исключены типы ссылок, кроме типа "компонент", в модели меню
Excluded types of links, except for the "component" type, in the menus model
